# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lucretius_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lucretius_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17lucretius_service.proto\":\n\x11\x43onnectionRequest\x12\x18\n\x10\x61pplication_name\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x03\"*\n\x12\x43onnectionResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\x08\"\x1b\n\x0cStartRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x03\" \n\rStartResponse\x12\x0f\n\x07\x63\x61n_run\x18\x01 \x01(\x08\"#\n\x14\x46inishedNotification\x12\x0b\n\x03pid\x18\x01 \x01(\x03\"\x1f\n\x0c\x44oneResponse\x12\x0f\n\x07\x61m_done\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xbd\x01\n\x10LucretiusService\x12\x32\n\x07\x63onnect\x12\x12.ConnectionRequest\x1a\x13.ConnectionResponse\x12&\n\x05start\x12\r.StartRequest\x1a\x0e.StartResponse\x12)\n\x08\x66inished\x12\x15.FinishedNotification\x1a\x06.Empty\x12\"\n\tam_i_done\x12\x06.Empty\x1a\r.DoneResponseB\r\n\tlucretiusP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lucretius_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tlucretiusP\001'
  _globals['_CONNECTIONREQUEST']._serialized_start=27
  _globals['_CONNECTIONREQUEST']._serialized_end=85
  _globals['_CONNECTIONRESPONSE']._serialized_start=87
  _globals['_CONNECTIONRESPONSE']._serialized_end=129
  _globals['_STARTREQUEST']._serialized_start=131
  _globals['_STARTREQUEST']._serialized_end=158
  _globals['_STARTRESPONSE']._serialized_start=160
  _globals['_STARTRESPONSE']._serialized_end=192
  _globals['_FINISHEDNOTIFICATION']._serialized_start=194
  _globals['_FINISHEDNOTIFICATION']._serialized_end=229
  _globals['_DONERESPONSE']._serialized_start=231
  _globals['_DONERESPONSE']._serialized_end=262
  _globals['_EMPTY']._serialized_start=264
  _globals['_EMPTY']._serialized_end=271
  _globals['_LUCRETIUSSERVICE']._serialized_start=274
  _globals['_LUCRETIUSSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
